### ISSUE TITLE
Error on vimrc: `Error: parse "": empty url`

### ISSUE THREAD

**Issue by rollschild** [neoclide/coc.nvim#3270]
Hi community, I've recently run into an issue when I opened up `.vimrc` using `NeoVim`, it gave me the following error:

```
[coc.nvim] parse "": empty url
[coc.nvim] Server languageserver.efm failed to start: Error: parse "": empty url
```

and `languageserver.efm` seems initializing itself forever but never finishes. Does anyone know what's this about?

I opened up an [issue](https://github.com/mattn/efm-langserver/issues/157#issue-959276444) on `efm-langserver` but [one comment](https://github.com/mattn/efm-langserver/issues/157#issuecomment-892237190) under that issue said that `efm-langserver` doesn't output log `empty url`.

The only `""` in my `.vimrc` is:
```
inoremap " ""<Esc>i
```
but I don't think it's causing the error.

`coc-settings.json`:

```
    "efm": {
      "command": "efm-langserver",
      "args": [],
      "filetypes": ["vim", "markdown"]
    },
```

Thanks in advance!

**Comment by fannheyward** [comment]
Can't reproduce, here is my coc-settings.json:

```json
{
  "languageserver": {
    "efm": {
      "command": "efm-langserver",
      "args": [],
      "filetypes": [
        "markdown"
      ]
    }
  }
}
```

and `.config/efm-langserver/config.yaml`

```yaml
languages:
  markdown:
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'
      - '%f:%l:%c %m'
      - '%f: %l: %m'
```
